### ISSUE TITLE
UI/UX - General

### ISSUE THREAD

**Issue by n3m8tz** [n3m8tz/snug-baby#10]
Web:
--Position of Menu/Logo/Title/Search
--Position of main box and colors

Mobile:
--Position Menu/Logo/Title/Search

**Comment by anlosty** [comment]
got it

**Comment by anlosty** [comment]
Hi! Look at that. I see an issue in case when we dont have a note. Let's discuss it.
![forweb](https://cloud.githubusercontent.com/assets/3118211/6877350/66fa8d00-d474-11e4-9d22-5f2f20790664.jpg)

**Comment by n3m8tz** [comment]
Looks awesome, I do see your point about white space though hmm.

**Comment by n3m8tz** [comment]
What about the logo? where can we fit it? left of SnugBaby?

**Comment by anlosty** [comment]
Hi! I will fit that tomorrow. Busy today

On Fri, Apr 3, 2015 at 8:11 PM, Ilya Grafutko <notifications@github.com>
wrote:

> What about the logo? where can we fit it? left of SnugBaby?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/n3m8tz/snug-baby/issues/10#issuecomment-89510311>.
>



-- 
Best,
Anastasia G.

**Comment by anlosty** [comment]
Hi! Check this out. I put logo and another icons
![babysnugready_3](https://cloud.githubusercontent.com/assets/3118211/6998584/ceeb6e4c-db82-11e4-8eb4-dac7e5bd81e8.jpg)
