### ISSUE TITLE
Defect: We want to open the same document each time we login

### ISSUE THREAD

**Issue by n3m8tz** [n3m8tz/snug-baby#3]
Right now each time I login into app it opens a new document for me, I want to see the same one

**Comment by AndrewSmarty** [comment]
As long as we press submit button( assume current url kinda "bla-bla-bla/snug-baby/#"), a client immediently posts a GET request to Google Drive Side and recently searched query "bla-bla-bla/snug-baby/#" will be replaced with "bla-bla-bla/snug-baby/#fileIds=our_files_id&userId=our_user_id"..

We r facing to the following problem: once we load an app in one browser(or a tab) GAPI engine generates a filesId1 and creates a new file, but if we load an app in the other browser(or a tab) GAPI engine generates a filesId2 and creates one more new file, so here we come. we dont actually want two or more files being created in Google drive, instead we want an only ONE and we want GAPI engine to search the drive for our app file each time we launch it in different browsers(tabs) to check in whether any relevant files were created whenever before so as to avoid multiple file existence

**Comment by genbit** [comment]
this is because of autoCreate: true option in gapi.realtime.js file
