### ISSUE TITLE
Get rid of "back" and "forward" buttons on the design

### ISSUE THREAD

**Issue by n3m8tz** [n3m8tz/snug-baby#4]
The back and forward are extra click for the user, ideally we want to eliminate them

![image](https://cloud.githubusercontent.com/assets/2198171/6472245/cd9ec5f8-c1a5-11e4-9105-0263ed6f543c.png)

**Comment by anlosty** [comment]
May I see the screen with those buttons?

**Comment by n3m8tz** [comment]
Uploaded, we see them typically in Event creation wizard.

**Comment by n3m8tz** [comment]
@EOdOW - Do you have a good suggestion?

**Comment by anlosty** [comment]
Can I see all mockups, to understand what happens before and after clicks?

**Comment by anlosty** [comment]
How I see it may be:
![addactivities_mockup](https://cloud.githubusercontent.com/assets/3118211/6474455/e88741c0-c1a4-11e4-8f4d-e282b53f25f3.jpg)

**Comment by anlosty** [comment]
That's just a mockup not ready design. In design I can make it more clear and simple

**Comment by n3m8tz** [comment]
Will it fit on a mobile? What if you have more acitvities? do u scroll right left? or more babies?

**Comment by anlosty** [comment]
Yes, it's iPhone 6 size. 
I gonna make baby icons with checkboxes more compact, so it possible to have 5-8 babies there.
It will be same for activity icons.
Or for some steps we can make an options where linked every step on this page and when user click on one of that, he will go to page with all choses.
I think that's better to have everything in one page. Because it's faster to use. This app should make parents life simpler, so they don't need to spend extra time to use it. 
I have same scheme on my expense tracker and it's work

**Comment by anlosty** [comment]
What u think?

**Comment by n3m8tz** [comment]
I love it!
In future I wanted to customize fields, for example end user might not want to specify ML ate or duration or breast, but just that the baby has eaten - so maybe fields can be hidden by default, etc.

**Comment by n3m8tz** [comment]
Btw the check boxes (circles) take space, would it be easier to just highlight the selection hmm?

**Comment by anlosty** [comment]
Might something like that
https://dribbble.com/shots/1011601-Inbox-wip?list=searches&offset=13
I'll create something like that

**Comment by anlosty** [comment]
Last version:
![babysnug_add-action](https://cloud.githubusercontent.com/assets/3118211/6758893/ce361286-cedf-11e4-944a-adecaddddf22.jpg)

**Comment by n3m8tz** [comment]
Hey!
I prefer the one w/o drop down. But we can try. Often I find it difficult to use drop down on mobile version

**Comment by anlosty** [comment]
hi!
i created that following material design conception. u can see how it works right there http://www.google.com/design/spec/components/menus.html#menus-behavior
but np, we can try another variants

**Comment by n3m8tz** [comment]
Hi. I think if we open cards by pressing on it. For example for date and time we use full screen cards. For babies we can have card similar to contacts, et

**Comment by n3m8tz** [comment]
My goal is to minimize number of clicks. So date time is preset. Babies can be squares same as contacts in android phone app. Full screen displaying 6-8 cards and scrollable. Same for activities. If one baby its preselected. For activities most commonly used, etc.

**Comment by n3m8tz** [comment]
Full screen dialogs for mobile and regular dialogs for other.

**Comment by anlosty** [comment]
Look at that:
![babysnug_add-action2](https://cloud.githubusercontent.com/assets/3118211/6838930/46ad8d42-d305-11e4-8fa5-e14949d54bed.jpg)

**Comment by anlosty** [comment]
created new avatars also
![avatar_boy](https://cloud.githubusercontent.com/assets/3118211/6839654/18e46b6e-d310-11e4-8b36-124197ccc811.png)
![avatar_girl](https://cloud.githubusercontent.com/assets/3118211/6839655/18e7941a-d310-11e4-94f3-655ffb86b2a9.png)
