### ISSUE TITLE
Display Date on main entries table

### ISSUE THREAD

**Issue by n3m8tz** [n3m8tz/snug-baby#9]
"Today,  December 18th"
"Yesterday, December 17th"
"December 16th"

**Comment by anlosty** [comment]
Check this out
![babysnug_mainfeed](https://cloud.githubusercontent.com/assets/3118211/6772153/78de607e-d09a-11e4-86a5-a4d338a39e9d.jpg)

**Comment by n3m8tz** [comment]
Nice yeah :) and we can do details after "feed - details"

**Comment by anlosty** [comment]
What do you mean? Explain pls.
